parse:
  additional_commands: {}

format:
  line_width: 80
  tab_size: 2
  use_tabchars: false
  max_pargs_hwrap: 3
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  line_ending: unix

markup:
  enable_markup: false
  bullet_char: '*'
  enum_char: .
