if(NOT CMAKE_SKIP_INSTALL_RULES)
    include(CMakePackageConfigHelpers)

    if(NOT DEFINED CMAKE_INSTALL_INCLUDEDIR)
        set(CMAKE_INSTALL_INCLUDEDIR "include")
    endif()
    if(NOT DEFINED CMAKE_INSTALL_DATADIR)
        set(CMAKE_INSTALL_DATADIR "share")
    endif()
endif()
